packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  electron: set this to true or false
  esbuild: set this to true or false

onlyBuiltDependencies:
  - bcrypt
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild
